apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysb
  template:
    metadata:
      labels:
        app: mysb
    spec:
      containers:
      - name: pod-mysb
        image: oolralra/spring:21
        ports:
        - containerPort: 8085
---
apiVersion: v1
kind: Service
metadata:
  name: svc-mysb
spec:
  type: NodePort
  selector:
    app: mysb
  ports:
  - nodePort: 31400
    port: 8085
    targetPort: 8085
